# @package _global_
# This is an exemplary local config file that you can adapt for your local configurations:
# E.g.: Only use CPU, or change the data_dir, or the input file names, or the number of workers for dataloading etc..
work_dir: ${oc.env:PSCRATCH}/convex-diffusion
