_target_: src.models.unet_convnext.UnetConvNext

defaults:
  - _self_
  - _base_model_config.yaml   # general, model independent, parameters

dim: 64
dim_mults: [1, 2, 4]      # [1, 2, 4, 8] does not work for 60x60 input with current setup
input_channels: null      # automatically inferred from the dataset/datamodule
output_channels: null     # automatically inferred from the dataset/datamodule
double_conv_layer: True   # Whether to use double convNext layer or not
output_mean_scale: False
residual: False

with_time_emb: False  # True

