_target_: pytorch_lightning.Trainer

gpus: 1    # -1 for all available GPUs. If you want to use CPU, set to 0.

min_epochs: 1
max_epochs: 50

gradient_clip_val: 1.0        # Gradient clipping at 1.0 of the norm
accumulate_grad_batches: 2    # Accumulate gradients on k batches

resume_from_checkpoint: null
precision: 32                 # 32 or 16
num_sanity_val_steps: 1       # number of validation steps to execute at the beginning of the training

