# ML model independen/agnostic hyperparameters (e.g. learning rate, batch size, etc.)

model.optimizer.lr: tag(log, interval(1e-5, 1e-2))   # log scale of learning rate
model.optimizer.weight_decay: tag(log, interval(1e-9, 0.1))   # log scale of weight decay
model.scheduler.gamma: choice(0.9, 0.96, 0.98, 0.99, 1.0)

# model.window: choice(1, 4)