defaults:
  - _self_
  - _base.yaml

_target_: src.diffusion.denoising_diffusion.GaussianDiffusion
timesteps: 1000
sampling_timesteps: null   # null means use all timesteps
beta_schedule: "cosine"
objective: "pred_noise"   # pred_x0, pred_noise
